"""Aded year_founded to company

Revision ID: 69314bc87c1b
Revises: 
Create Date: 2021-01-27 22:57:33.291665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69314bc87c1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('year_founded', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'year_founded')
    # ### end Alembic commands ###
